# Generated by Django 5.0.3 on 2024-03-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('notComplete', 'Not Complete')], default='notComplete', max_length=20, null=True),
        ),
    ]
